# ============================================================================
# CORRECTED: 01-namespace.yaml
# FIX: Changed ingresses.networking.k8s.io to use count/ prefix
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    name: ${NAMESPACE}
    environment: ${ENVIRONMENT}
    team: ${TEAM}
    app.kubernetes.io/managed-by: kubectl
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
  annotations:
    description: "Namespace for ${APP_NAME} application in ${ENVIRONMENT} environment"
    contact: "${TEAM}@company.com"
    created-by: "k8s-template-v2.0"
spec:
  finalizers: [ "kubernetes" ]
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${NAMESPACE}-quota
  namespace: ${NAMESPACE}
  labels:
    component: resource-management
    app.kubernetes.io/part-of: ${APP_NAME}
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: "4Gi"
    limits.cpu: "4000m"
    limits.memory: "8Gi"
    requests.storage: "100Gi"
    persistentvolumeclaims: "5"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
    count/ingresses.networking.k8s.io: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ${NAMESPACE}-limits
  namespace: ${NAMESPACE}
  labels:
    component: resource-management
    app.kubernetes.io/part-of: ${APP_NAME}
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 500Mi
    max:
      cpu: 2000m
      memory: 2Gi
      ephemeral-storage: 5Gi
    min:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 100Mi
  - type: PersistentVolumeClaim
    max:
      storage: 50Gi
    min:
      storage: 1Gi
---

